name: .NET Core Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'  # Update to the version you are using

    - name: List directory contents
      run: |
        dir /s /b  # List all files and directories recursively

    - name: Restore dependencies
      run: dotnet restore ./CircusTreinUnitTests/CircusTrein.Domein/CircusTrein.UnitTests/CircusTrein.UnitTests.csproj

    - name: Build
      run: dotnet build ./CircusTreinUnitTests/CircusTrein.Domein/CircusTrein.UnitTests/CircusTrein.UnitTests.csproj --configuration Release

    - name: Test
      run: dotnet test ./CircusTreinUnitTests/CircusTrein.Domein/CircusTrein.UnitTests/CircusTrein.UnitTests.csproj --configuration Release --verbosity normal
