name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Update to v3 for Node.js 20

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3  # Update to v3 for Node.js 20
      with:
        dotnet-version: '8.0.x'  # Ensure .NET 8.0 is compatible with Node.js 20

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
