name: .NET Core Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Update to v3 for latest version

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3  # Update to v3 for latest version
      with:
        dotnet-version: '8.0.x'  # Ensure .NET 8.0 is compatible with Node.js 20

    - name: List directory contents
      run: |
        ls -lR  # List all files and directories recursively for verification

    - name: Restore dependencies for Main Project
      run: dotnet restore ./CircusTrein.Domein/CircusTrein.Domein.csproj
      working-directory: ./CircusTrein.Domein

    - name: Build Main Project
      run: dotnet build --configuration Release ./CircusTrein.Domein/CircusTrein.Domein.csproj
      working-directory: ./CircusTrein.Domein

    - name: List directory contents of Unit Tests
      run: |
        ls -lR  # List all files and directories recursively for verification
      working-directory: ./CircusTrein.Domein/CircusTrein.UnitTests

    - name: Test
      run: dotnet test --configuration Release ./CircusTrein.Domein/CircusTrein.UnitTests/CircusTrein.UnitTests.csproj
      working-directory: ./CircusTrein.Domein/CircusTrein.UnitTests

    - name: Build and Test Unit Tests
      run: |
        dotnet build --configuration Release ./CircusTrein.Domein/CircusTrein.UnitTests/CircusTrein.UnitTests.csproj
        dotnet test --configuration Release --verbosity normal ./CircusTrein.Domein/CircusTrein.UnitTests/CircusTrein.UnitTests.csproj
      working-directory: ./CircusTrein.Domein/CircusTrein.UnitTests
