name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Update to latest version of actions/checkout
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v4  # Update to latest version of actions/setup-node
      with:
        node-version: '20'  # Set Node.js version to 20

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4  # Update to latest version of actions/setup-dotnet
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
