name: .NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3  # Updated to v3
      with:
        dotnet-version: '8.0.x'  # Updated to .NET 8.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
